language: go
go:
- 1.2
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
before_install:
- go get github.com/tools/godep
- godep restore
addons:
  artifacts:
    bucket: meatballhat
    permissions: public-read
    paths:
    - ${GOPATH%%:*}/bin/pierolog
    - $(git ls-files -o | tr "\n" ":")
    key:
      secure: PdM6qPYisOXWD8fLGYjeoPW3SJYX13BnAS+pF+0yM2iAUzG6zrJvhvcIU8uMjN+RaiY8ypaGprzMEiyoJTQ9KHnQ5qMZL1g93YIyD0ewMcMP16VH2NEnh/qYujlEm0qt80lpICSPNF/62Z43fDAYO2Wxt+cXIbcVY/aovEha7UI=
    secret:
      secure: CAfTXzOzGiKe2VGvJ6Vz1+K341MxreMoe4mjCWczWQWwDeJNAZ1LmAN/8y6NlkjPSlITTqPTCGo4IDyCu13kDk3PVTwHjFAinHps2ugT3z7hXrfQ1i1DBiPYe1Qzw7ZF26ejntjO3MzfNuN4cR8Up1gI6r30C+4sOxk5yDdUu/s=
