language: go
go:
- 1.2
env:
  global:
  - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
before_install:
- go get github.com/tools/godep
- godep restore
addons:
  artifacts:
    bucket: meatballhat
    permissions: public-read
    paths:
    - ${GOPATH%%:*}/bin/pierolog
    - $(git ls-files -o | tr "\n" ":")
    key:
      secure: M2qXiTEb9t1YPhRNr0heRWEfNVC+3fCZt/GMYTQmQ3GFb3G+3h1JYvXxM8xJGKe+vmFIeWXjm6FQl7TJTAsQ+fININeoRzapQ1qXc3ekp5JFSotL1DD8IA1zrM+qeY2B0OVjNHb9df2ExNJWiZ4J1lUTCP2MwocDAmKvFSXEVxs=
    secret:
      secure: G7y2ldWhCEymlmoI9+MgCxsV58BpmiyIGRGPZ4bs6jZXmAV4zo1Gdst6N2Qqq0XEt2gvva7LeQBU0tpBdIjyh2C5G+P7sZTAiO+dfyAulHZIDZrjEFm39+aL5ATHZIp+8XlbuSJneIVPWnT0A5RVW3RlcwoEeC1UP0xUAhvaMpI=
